export const GET_PHOTOS = "GET_PHOTOS";
export const SET_PHOTOS = "SET_PHOTOS";
export const GET_PHOTOS_SCROLL = "GET_PHOTOS_SCROLL";
export const SET_PHOTOS_SCROLL = "SET_PHOTOS_SCROLL";
export const SET_PHOTOS_ERROR = "SET_PHOTOS_ERROR";
